{% set name = "texttable" %}
{% set version = "1.6.7" %}
{% set sha256 = "290348fb67f7746931bcdfd55ac7584ecd4e5b0846ab164333f0794b121760f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps --ignore-installed

requirements:
  host:
    - pip
    - python =2.7|>=3.5
    - setuptools

  run:
    - python =2.7|>=3.5

test:
  imports:
    - texttable

about:
  home: https://github.com/foutaise/texttable/
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Python module for creating simple ASCII tables
  description: texttable is a module to generate a formatted text table, using ASCII characters.
  doc_url: https://github.com/foutaise/texttable#documentation
  dev_url: https://github.com/foutaise/texttable/

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
    - micknudsen
